### PR TITLE
Add a toggle button to turn the extension on/off

### PR DESCRIPTION
**Pull request by vivi2004**
Hey  I added  a toggle button to turn the extension  on/ off...   that works fine  and looks pretty..
> I added the icon to "  Reload to apply "  so that  after all  refresh  this icon  it refresh and  show some cool stuffs..
> I seprate the html and css so  that of the clean code that would helps other to save changes and  it seems a clean code..

### CODE REVIEW

**Comment by vivi2004** [comment]
Screenshot 2024-10-02 172637
  And I centred it to fron of the web page   that looks good though..

**Comment by whirlxd** [comment]
since you added a button just remove the enable extension checkbox

**Comment by vivi2004** [comment]
> since you added a button just remove the enable extension checkbox

Ok I  will ...

**Comment by vivi2004** [comment]
Screenshot 2024-10-02 175942
Hey check I have updated one...

**Pull request merged**
